### PR TITLE
Zachary cj decker contrib

### PR DESCRIPTION
**Pull request by ZacharyCJDecker**

### CODE REVIEW

**Review by annaposlednik — APPROVED** [review]
Looks good!

**Comment by lauren-alexandra** [comment]
URL should be updated to your GitHub Pages portfolio site

**Comment by lauren-alexandra** [comment]
URL should be updated to your GitHub Pages portfolio site

**Comment by nquarder** [comment]
Hey @ZacharyCJDecker - nice work with this so far.

It looks like the text you added to your portfolio page in the 3rd column isn't linked. You can edit this text using Markdown to link to your portfolio page.

The syntax will look something like [username.github.io](https://github.com/earthlab-education/Earth-Analytics-AY24/pull/username.github.io)

Here is a link to the Markdown guide that explains the syntax in more detail: https://www.markdownguide.org/basic-syntax/#links

You can try re-editing the README.md file to include this Markdown syntax and then resubmitting the Pull Request. Thanks! -NQ

**Review by cmq879 — CHANGES_REQUESTED** [review]
I would recommend changing the profile URL in your line to: [zacharycjdecker.github.io](https://zacharycjdecker.github.io/)
As is, it displays your GitHub profile URL but the link goes to your portfolio page

**Comment by cmq879** [comment]
> I would recommend changing the profile URL in your line to: open bracket zacharycjdecker.github.io closed bracket open parenthesis https://zacharycjdecker.github.io/ closed parenthesis 
As is, it displays your GitHub profile URL but the link goes to your portfolio page

**Comment by ZacharyCJDecker** [comment]
> I would recommend changing the profile URL in your line to: [zacharycjdecker.github.io](https://zacharycjdecker.github.io/) As is, it displays your GitHub profile URL but the link goes to your portfolio page

Okay, I've changed this!

**Review by cmq879 — APPROVED** [review]

**Review by annaposlednik — APPROVED** [review]

**Pull request merged**
