### PR TITLE
Update Erin Zimmerman Info.md

### PR DESCRIPTION
**Pull request by ZimmZone**

### CODE REVIEW

**Review by npwelsh — COMMENTED** [review]
Just missing the URL, everything else looks good though!

**Review by reidhan — COMMENTED** [review]
Name and GitHub Username columns look good. Make sure to add Portfolio URL once that's ready.

**Comment by nquarder** [comment]
Hey @ZimmZone  - nice work with this so far.

It looks like the text you added to your portfolio page in the 3rd column isn't linked. You can edit this text using Markdown to link to your portfolio page.

The syntax will look something like [username.github.io](username.github.io)

Here is a link to the Markdown guide that explains the syntax in more detail: https://www.markdownguide.org/basic-syntax/#links

You can try re-editing the README.md file to include this Markdown syntax and then resubmitting the Pull Request. Thanks! -NQ

**Comment by nquarder** [comment]
Now we're talking, @ZimmZone - nicely done! 😎

**Pull request merged**
