### PR TITLE
First map post and update README with contributor

### PR DESCRIPTION
**Pull request by lauren-alexandra**
# First map post and update README with contributor

Addresses Issue (start typing # to see a list of issues) #180 

**Before you submit, remember to:**
- [x] Pull in all changes from main to reduce conflicts
- [x] Request reviews from @earthlab-education/ea-students

### CODE REVIEW

**Review by hanried — CHANGES_REQUESTED** [review]
Hi Lauren! Your updates on the README.md look good. Your enf-map.md and enf-map.html also look good. 
Change requested: I don't think I see your map on your portfolio website. It's the very last step on the textbook page for the map assignment: https://cu-esiil-edu.github.io/esiil-learning-portal/foundations/pages/03-git-github/03-github-portfolio/05-map.html
Small update after watching Elsa's video about how to review each other's code: Good job also with sourcing that you pulled your ENF info from the US Forest Service.

**Comment by lauren-alexandra** [comment]
@hanried Thank you for your feedback. I updated the portfolio with the map as well: https://lauren-alexandra.github.io.

**Review by hanried — DISMISSED** [review]
Nice update on your portfolio website, the map shows up well!

**Review by WillToon — APPROVED** [review]
@lauren-alexandra great map, I think it looks good on your profile. I appreciate that you adjusted the scaling for your map and the only thing that I might add is a hyperlink to the national forest website!

**Review by byandell — COMMENTED** [review]
Looks good to me.

**Review by byandell — COMMENTED** [review]
Looks good to me.

**Pull request merged**
