### PR TITLE
Update README.md w/ new username for Hannah Rieder and first map portfolio post

### PR DESCRIPTION
**Pull request by hanried**
#110 

Adresses Issue - Changed username to make more sense with my actual name. Updated GitHub Username and Portfolio URL columns.

**Before you submit, remember to:**
- [x] Pull in all changes from main to reduce conflicts
- [x] Request reviews from @earthlab-education/ea-students

### CODE REVIEW

**Review by elyna-grapstein — CHANGES_REQUESTED** [review]
Does not reflect the most current version of the table.

**Review by lauren-alexandra — DISMISSED** [review]
Portfolio looks good but need to pull in changes from main before merging

**Comment by hanried** [comment]
@elyna-grapstein I think I've merged the main branch to my branch, would you mind reviewing again? thanks!

**Review by lauren-alexandra — APPROVED** [review]
Changes and portfolio map look good

**Review by cmq879 — DISMISSED** [review]
Map on profile - check! looks good

**Review by annaposlednik — APPROVED** [review]

**Review by annaposlednik — APPROVED** [review]

**Review by cmq879 — APPROVED** [review]

**Comment by hanried** [comment]
@annaposlednik and @cmq879 would you mind approving this pull request for me again? I had to merge the main branch updates to my branch this morning and doing that deleted your approvals again. Thanks in advance!

**Review by annaposlednik — DISMISSED** [review]

**Comment by hanried** [comment]
@annaposlednik your review got dismissed again. @annaposlednik and @cmq879 would you be able to please approve again? Apologies that this keeps happening!

**Comment by eculler** [comment]
@hanried I merged this in, nice work!

**Pull request merged**
