### PR TITLE
Annaposlednik first map upload

### PR DESCRIPTION
**Pull request by annaposlednik**

### CODE REVIEW

**Review by ZacharyCJDecker — DISMISSED** [review]
You're missing the URL

**Review by lauren-alexandra — DISMISSED** [review]
URL works

**Comment by nquarder** [comment]
Hi @annaposlednik - what you have here looks great. It does appear you are missing a minor detail in the link to your portfolio URL. 

Try adding `https://` in front of `username.github.io` text inside the parentheses in Column 3. 

So, something like: `[username.github.io](https://username.github.io)` 

This is something I overlooked too in my initial Pull Request, and something I forgot to mention in some of my initial comments/reviews to others' Pull Requests. Ooops! Going back to fix now ;) -NQ

**Comment by allierosel** [comment]
Looks great @annaposlednik but still needs the URL to be fixed.

**Review by atticusbaker — COMMENTED** [review]
I think this looks good!

**Review by gpb3037 — COMMENTED** [review]
looks good to me

**Review by gpb3037 — APPROVED** [review]
oops forgot to approve on previous comment

**Review by ZacharyCJDecker — DISMISSED** [review]

**Comment by annaposlednik** [comment]
@allierosel @ZacharyCJDecker could you review my pull requests thanks!

**Review by ZacharyCJDecker — APPROVED** [review]

**Review by hanried — APPROVED** [review]

**Pull request merged**
