### PR TITLE
Adding my species distribution portfolio post

### PR DESCRIPTION
**Pull request by annaposlednik**
# Pull Request Description Here

Adresses Issue (start typing # to see a list of issues)

**Before you submit, remember to:**
- [ ] Pull in all changes from main to reduce conflicts
- [ ] Request reviews from @earthlab-education/ea-students

### CODE REVIEW

**Review by BioNCphilic — CHANGES_REQUESTED** [review]
It's been a while since we did reviews so you'll see my comments on the pull request as well. Here are my suggestions:
1. For the migration plot - did you post it as an html file? My browser says the plugin is not supported.
2. Your code does not show how you extracted the data and plotted it. The rubric for this assignment has three components which are all code related. Although you give a nice description of your methods.

**Comment by annaposlednik** [comment]
I've now updated the osprey migration html to include a link to my data (ipynb notebook) and the plot is now showing on the portfolio post. This pull request will also update my other portfolio posts (climate and redlining) in addition to species distribution

**Review by BioNCphilic — APPROVED** [review]
Code and interactive map both accessible. Nice work.

**Review by tjstogoski — APPROVED** [review]
Looks good. All your figures and graphics displayed nicely for me.

**Pull request merged**
