### PR TITLE
Gpb3037 contrib

### PR DESCRIPTION
**Pull request by gpb3037**
not sure how to define location - I see others with username.github.io but when I look for that or try to create it there is nothing found on the web.  Thus I have listed it as unknown.

### CODE REVIEW

**Comment by gpb3037** [comment]
ok found https://cu-esiil-edu.github.io/esiil-learning-portal/foundations/pages/00-course-overviews/foundations/01-fundamentals/01-portfolio.html and got started with that instead of just the email for scavenger hunt and setup first page.

**Review by tjstogoski — APPROVED** [review]
Looks good!

**Comment by gpb3037** [comment]
forgot to list it as #20

**Review by lauren-alexandra — APPROVED** [review]
URL works

**Pull request merged**
