### PR TITLE
Reidhan contrib

### PR DESCRIPTION
**Pull request by reidhan**
reidhan submitting to issue #88 Scavenger Hunt.
Tagging owner of repository @eculler

### CODE REVIEW

**Review by nquarder — COMMENTED** [review]
Hey @reidhan  - nice work with this so far.

It looks like the text you added to your portfolio page in the 3rd column isn't linked. You can edit this text using Markdown to link to your portfolio page.

The syntax will look something like [username.github.io](username.github.io)

Here is a link to the Markdown guide that explains the syntax in more detail: https://www.markdownguide.org/basic-syntax/#links

You can try re-editing the README.md file to include this Markdown syntax and then resubmitting the Pull Request. Thanks! -NQ

**Review by atticusbaker — COMMENTED** [review]
Link to website is not working, but I can copypaste

**Review by nquarder — DISMISSED** [review]
Now it's working @reidhan - great job! -NQ

**Review by cmq879 — DISMISSED** [review]
Nice!

**Pull request merged**
