### PR TITLE
Atticusbaker contrib

### PR DESCRIPTION
**Pull request by atticusbaker**
#78 Submission.

### CODE REVIEW

**Review by nquarder — CHANGES_REQUESTED** [review]
Nice job w/ this @atticusbaker! I like how you're trying to link to both your GitHub profile (column 2) **and** GitHub portfolio (column 3). However, it looks like the link to your profile (see column 2) isn't working. Trying adding `https://` to the front of text `github.com/atticusbaker` inside the parentheses and then commit those changes.

Give that a shot and let's see how things look from there. Thanks! -NQ

**Comment by atticusbaker** [comment]
How does that look?

**Review by nquarder — DISMISSED** [review]
looking good @atticusbaker - and your portfolio page is looking great too. nicely done! -NQ

**Review by cmq879 — APPROVED** [review]
Looks good!

**Pull request merged**
