### PR TITLE
brglea - update portfolio/scavenger hunt week 1 + First Map Post week 2

### PR DESCRIPTION
**Pull request by brglea**
#118 scavenger hunt, added my info to the README file + #171 Coding Challenge for First Map post

### CODE REVIEW

**Comment by allierosel** [comment]
Looks like you added this to the main when it should have been just for your branch. It also needs to include a link using the []() method

**Comment by allierosel** [comment]
Wait I think I was wrong it does look like it is in your branch. Apologies!

**Review by nquarder — CHANGES_REQUESTED** [review]
Hey @brglea and great job with this. It looks like the link to your GitHub portfolio isn't working in column 3. Try adding `https://` to the front of the `brglea.github.io` text and then committing those changes. 

Thanks! -NQ

**Review by hanried — CHANGES_REQUESTED** [review]
Hi! The first two columns with your name and username look great. I think you need to add your portfolio link to the third column using markdown syntax. In the third column, I think your username.github.io would be in [] and then https://username.github.io is in () after that. There's more info here: https://www.markdownguide.org/basic-syntax/#links
Apologies for not reviewing this sooner, I didn't realize I had been assigned to review this until today.

**Comment by brglea** [comment]
@nquarder and @hanried I think I have fixed what I have needed to, when I first submitted this pull request I hadn't created my portfolio yet, my portfolio has since been created, my bad. I didn't realize it should have been creating the portfolio first, before trying to do a pull request. 

I also submitted a separate pull request to get up to date with the main branch, so I'm not sure if I need to wait for that to go through and then readjust this as needed? I will also need to update this for the first map challenge I think (I've finished my map and am currently watching Elsa's tutorial on how to add that to posts, so maybe that's unrelated to this pull request, not sure yet.

Thank you for both of your reviews :)

**Review by hanried — APPROVED** [review]
Hey! Everything on the README.md file looks great and your portfolio looks good too, the first map is showing up well on your portfolio! 
gmcc2.html - this file of your map looks all good.
gmcc_map (3).md - this markdown file also looks good to me, nice job adding the reference in.

**Comment by eculler** [comment]
@brglea this looks great! That's a beautiful map -- I love looking at old cities from above. And the context about the history of the Mosque and its later expansions make it that much more interesting. I'm going to go ahead and merge your PR.

**Pull request merged**
