### PR TITLE
Add Allie's info to README.md

### PR DESCRIPTION
**Pull request by allierosel**
@eculler Hey Elsa, adding my info to the readme

### CODE REVIEW

**Review by gpb3037 — APPROVED** [review]
looks good to me

**Review by akpost21 — COMMENTED** [review]
@allierosel Looks good!

**Review by akpost21 — APPROVED** [review]
@allierosel Looks good!

**Comment by eculler** [comment]
@allierosel This is a great start! Could you change this so that it has an active link to your portfolio page? It will look something like [Allie's Portfolio](allierosel.github.io) in your document. You may need to create a new pull request, because I had merged this one before realizing the link wouldn't come up (oops!).

**Pull request merged**
