### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by WillToon**

### CODE REVIEW

**Review by annaposlednik — DISMISSED** [review]
Looks good, although not sure the url works yet

**Review by ZimmZone — COMMENTED** [review]
If this is your actual URL I think you need to add it using something similar to what Anna used

` [akpost21.github.io](akpost21.github.io) `

 I think you need to add it with  HTML in Markdown cells to create hyperlinks to websites using the following syntax:

a href="url" target="_blank">hyperlinked words</a

You can identify the words that will be hyperlinked (i.e. prompt a web page to open when clicked) by replacing hyperlinked words in the example above.
I found this in the Unit 1 'Format Text with Markdown'

**Review by npwelsh — COMMENTED** [review]
Looks good, link doesn't work yet (I need to update mine too)

**Comment by nquarder** [comment]
Nice job @WillToon - I see @ZimmZone gave some great advice up above. It looks like you have everything in place, and are using the correct Markdown syntax. However in the 3rd column you are linking to your GitHub profile (https://github.com/WillToon) rather than what we're calling your GitHub portfolio (willtoon.github.io), which looks like has yet to be published. 

Give that a chance when you get some time and then re-edit the README.md file with the update link/text. Thanks! -NQ

**Comment by WillToon** [comment]
Thanks everyone, I appreciate the suggestions and unfortunately didn't have the time to go through the lecture last week. It should be displaying a correct link to my portfolio now though. Please let me know if it works for you all!

**Review by cmq879 — APPROVED** [review]
The link to your portfolio page works for me.

**Review by VictoriAragon — APPROVED** [review]
@WillToon nice job with your portfolio

**Review by BioNCphilic — APPROVED** [review]
@WillToon and @nquarder  and @VictoriAragon - thanks for the example on using html markup and also the approval process.

**Comment by eculler** [comment]
Looks great @WillToon , thanks to everyone for their help reviewing this PR!

**Pull request merged**
