### PR TITLE
Scavenger hunt exercise

### PR DESCRIPTION
**Pull request by BioNCphilic**
Working on the checklist for the scavenger hunt. #63

### CODE REVIEW

**Review by gpb3037 — COMMENTED** [review]
Not sure whether you need to first create BioNCphilic.GitHub.io as I don't see it functional as of yet

**Comment by BioNCphilic** [comment]
> Not sure whether you need to first create BioNCphilic.GitHub.io as I don't see it functional as of yet

Thanks. I believe @eculler or @nquarder have to make it functional first.

**Review by gpb3037 — APPROVED** [review]
looks like it works now!

**Review by nquarder — CHANGES_REQUESTED** [review]
Hi @BioNCphilic - great start with this! It looks like your portfolio page is active (https://bioncphilic.github.io) - nice!

To link to your portfolio in the README.md you can do either: 

1.) add `https://` to the start of `BioNCphilic.github.io` text in Column 3

2.) Use Markdown syntax like the following: `[username.github.io](https://username.github.io)`

Give one of these a try and save your changes in the README.md file. Thanks. -NQ

**Review by VictoriAragon — DISMISSED** [review]
@BioNCphilic great job i like it @nquarder

**Pull request merged**
